version: '3.8'

services:
  keycloak:
    container_name: keycloak_NextJs
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9080:8080"
    command: start-dev
    networks:
      - local_network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: font_client_docker
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: mysecretpassword


networks:
  local_network:
    external: true